# Generated by Django 5.1.7 on 2025-03-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_budget_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='transaction',
        ),
    ]
